/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PesquisasRouteImport } from './routes/pesquisas'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as EquipaRouteImport } from './routes/equipa'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as DepartamentoSlugRouteImport } from './routes/departamento.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasRoute = PesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipaRoute = EquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const DepartamentoSlugRoute = DepartamentoSlugRouteImport.update({
  id: '/departamento/$slug',
  path: '/departamento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contactos': typeof ContactosRoute
  '/equipa': typeof EquipaRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/departamento/$slug': typeof DepartamentoSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contactos': typeof ContactosRoute
  '/equipa': typeof EquipaRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/departamento/$slug': typeof DepartamentoSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contactos': typeof ContactosRoute
  '/equipa': typeof EquipaRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/departamento/$slug': typeof DepartamentoSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contactos'
    | '/equipa'
    | '/noticias'
    | '/pesquisas'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/departamento/$slug'
    | '/noticias/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contactos'
    | '/equipa'
    | '/noticias'
    | '/pesquisas'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/departamento/$slug'
    | '/noticias/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contactos'
    | '/equipa'
    | '/noticias'
    | '/pesquisas'
    | '/servicos'
    | '/sitemap.xml'
    | '/sobre'
    | '/departamento/$slug'
    | '/noticias/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactosRoute: typeof ContactosRoute
  EquipaRoute: typeof EquipaRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  PesquisasRoute: typeof PesquisasRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  DepartamentoSlugRoute: typeof DepartamentoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas': {
      id: '/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof PesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipa': {
      id: '/equipa'
      path: '/equipa'
      fullPath: '/equipa'
      preLoaderRoute: typeof EquipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/departamento/$slug': {
      id: '/departamento/$slug'
      path: '/departamento/$slug'
      fullPath: '/departamento/$slug'
      preLoaderRoute: typeof DepartamentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactosRoute: ContactosRoute,
  EquipaRoute: EquipaRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  PesquisasRoute: PesquisasRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  DepartamentoSlugRoute: DepartamentoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
